package kutuphane;

import static java.lang.StrictMath.toIntExact;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Hatice Ertürk
 */
public class CezaOdeme extends javax.swing.JFrame {
    private Connection baglanti;
    private Statement ifade;
    String kim;
    
    public CezaOdeme() {
        initComponents();
        DBBaglan();
        baslangic();
    }

    private void baslangic(){
        buttonGroup1.add(jRadioButtonOgrenci);
        buttonGroup1.add(jRadioButtonOgretmen);
        buttonGroup1.add(jRadioButtonDisaridan);
        jPanelOgrenci.setVisible(false);
        jPanelOgretmen.setVisible(false);
        jPanelDisaridan.setVisible(false);
        jPanelOdenecekOgrenci.setVisible(false);
    }
    
    private void DBBaglan(){
        String baglantiUrl = "jdbc:derby://localhost:1527/Kutuphane";
        String userName = "hatice";
        String password = "123";
        
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            baglanti = DriverManager.getConnection(baglantiUrl,userName,password);
            ifade = baglanti.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
        catch (ClassNotFoundException e){
            e.printStackTrace();
        }
    }    
    
    private long time(String tarih1,String tarih2){
        SimpleDateFormat myFormat = new SimpleDateFormat("yyyy-MM-dd");
        String inputString1 = tarih1;
        String inputString2 = tarih2;
        try {
            Date date1 = myFormat.parse(inputString1);
            Date date2 = myFormat.parse(inputString2);
            long diff = date2.getTime() - date1.getTime();
            return TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);
           // System.out.println (TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS));
        } catch (ParseException e) {
            e.printStackTrace(); 
        }
        return 0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButtonOgretmen = new javax.swing.JRadioButton();
        jRadioButtonOgrenci = new javax.swing.JRadioButton();
        jRadioButtonDisaridan = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPanelOgrenci = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTC = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanelOdenecekOgrenci = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelToplamCeza = new javax.swing.JLabel();
        jButtonCezayiode = new javax.swing.JButton();
        jPanelOgretmen = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldOgretmenTC = new javax.swing.JTextField();
        jButtonCezaGoruntuleOgretmen = new javax.swing.JButton();
        jPanelOdenecekOgretmen = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabelToplamCezaOgretmen = new javax.swing.JLabel();
        jButtonCezayiodeOgretmen = new javax.swing.JButton();
        jPanelDisaridan = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDisaridanTC = new javax.swing.JTextField();
        jButtonCezaGoruntuleDisaridan = new javax.swing.JButton();
        jPanelOdenecekDisaridan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelToplamCezaDisaridan = new javax.swing.JLabel();
        jButtonCezayiodeDisaridan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setPreferredSize(new java.awt.Dimension(436, 400));

        jRadioButtonOgretmen.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        jRadioButtonOgretmen.setText("Öğretmen");
        jRadioButtonOgretmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOgretmenActionPerformed(evt);
            }
        });

        jRadioButtonOgrenci.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        jRadioButtonOgrenci.setText("Öğrenci");
        jRadioButtonOgrenci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOgrenciActionPerformed(evt);
            }
        });

        jRadioButtonDisaridan.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        jRadioButtonDisaridan.setText("Dışarıdan");
        jRadioButtonDisaridan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDisaridanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabel3.setText("Ödeme Yapacak Üyenin Tipini Seçiniz : ");

        jLabel1.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabel1.setText("Öğrenci Okul Numarasını Giriniz : ");

        jTextFieldTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTCActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setText("Ceza Görüntüle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabel2.setText("Ödenecek Toplam Ceza Tutarı : ");

        jLabelToplamCeza.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        jButtonCezayiode.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButtonCezayiode.setText("Cezayı Öde");
        jButtonCezayiode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCezayiodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOdenecekOgrenciLayout = new javax.swing.GroupLayout(jPanelOdenecekOgrenci);
        jPanelOdenecekOgrenci.setLayout(jPanelOdenecekOgrenciLayout);
        jPanelOdenecekOgrenciLayout.setHorizontalGroup(
            jPanelOdenecekOgrenciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOdenecekOgrenciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelToplamCeza, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOdenecekOgrenciLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCezayiode, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        jPanelOdenecekOgrenciLayout.setVerticalGroup(
            jPanelOdenecekOgrenciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOdenecekOgrenciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOdenecekOgrenciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelToplamCeza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCezayiode)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout jPanelOgrenciLayout = new javax.swing.GroupLayout(jPanelOgrenci);
        jPanelOgrenci.setLayout(jPanelOgrenciLayout);
        jPanelOgrenciLayout.setHorizontalGroup(
            jPanelOgrenciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOgrenciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldTC, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanelOgrenciLayout.createSequentialGroup()
                .addGroup(jPanelOgrenciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOgrenciLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelOgrenciLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelOdenecekOgrenci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOgrenciLayout.setVerticalGroup(
            jPanelOgrenciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOgrenciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOgrenciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelOdenecekOgrenci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabel4.setText("Öğretmenin TC Numarasını Giriniz : ");

        jTextFieldOgretmenTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOgretmenTCActionPerformed(evt);
            }
        });

        jButtonCezaGoruntuleOgretmen.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButtonCezaGoruntuleOgretmen.setText("Ceza Görüntüle");
        jButtonCezaGoruntuleOgretmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCezaGoruntuleOgretmenActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabel5.setText("Ödenecek Toplam Ceza Tutarı : ");

        jLabelToplamCezaOgretmen.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        jButtonCezayiodeOgretmen.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButtonCezayiodeOgretmen.setText("Cezayı Öde");
        jButtonCezayiodeOgretmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCezayiodeOgretmenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOdenecekOgretmenLayout = new javax.swing.GroupLayout(jPanelOdenecekOgretmen);
        jPanelOdenecekOgretmen.setLayout(jPanelOdenecekOgretmenLayout);
        jPanelOdenecekOgretmenLayout.setHorizontalGroup(
            jPanelOdenecekOgretmenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOdenecekOgretmenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelToplamCezaOgretmen, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOdenecekOgretmenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCezayiodeOgretmen, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        jPanelOdenecekOgretmenLayout.setVerticalGroup(
            jPanelOdenecekOgretmenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOdenecekOgretmenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOdenecekOgretmenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelToplamCezaOgretmen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCezayiodeOgretmen)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout jPanelOgretmenLayout = new javax.swing.GroupLayout(jPanelOgretmen);
        jPanelOgretmen.setLayout(jPanelOgretmenLayout);
        jPanelOgretmenLayout.setHorizontalGroup(
            jPanelOgretmenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOgretmenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldOgretmenTC, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
            .addGroup(jPanelOgretmenLayout.createSequentialGroup()
                .addGroup(jPanelOgretmenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOgretmenLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButtonCezaGoruntuleOgretmen, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelOgretmenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelOdenecekOgretmen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanelOgretmenLayout.setVerticalGroup(
            jPanelOgretmenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOgretmenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOgretmenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOgretmenTC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCezaGoruntuleOgretmen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelOdenecekOgretmen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabel6.setText("Öğretmenin TC Numarasını Giriniz : ");

        jTextFieldDisaridanTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDisaridanTCActionPerformed(evt);
            }
        });

        jButtonCezaGoruntuleDisaridan.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButtonCezaGoruntuleDisaridan.setText("Ceza Görüntüle");
        jButtonCezaGoruntuleDisaridan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCezaGoruntuleDisaridanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabel7.setText("Ödenecek Toplam Ceza Tutarı : ");

        jLabelToplamCezaDisaridan.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        jButtonCezayiodeDisaridan.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButtonCezayiodeDisaridan.setText("Cezayı Öde");
        jButtonCezayiodeDisaridan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCezayiodeDisaridanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOdenecekDisaridanLayout = new javax.swing.GroupLayout(jPanelOdenecekDisaridan);
        jPanelOdenecekDisaridan.setLayout(jPanelOdenecekDisaridanLayout);
        jPanelOdenecekDisaridanLayout.setHorizontalGroup(
            jPanelOdenecekDisaridanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOdenecekDisaridanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelToplamCezaDisaridan, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOdenecekDisaridanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCezayiodeDisaridan, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        jPanelOdenecekDisaridanLayout.setVerticalGroup(
            jPanelOdenecekDisaridanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOdenecekDisaridanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOdenecekDisaridanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelToplamCezaDisaridan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCezayiodeDisaridan)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout jPanelDisaridanLayout = new javax.swing.GroupLayout(jPanelDisaridan);
        jPanelDisaridan.setLayout(jPanelDisaridanLayout);
        jPanelDisaridanLayout.setHorizontalGroup(
            jPanelDisaridanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDisaridanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldDisaridanTC, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
            .addGroup(jPanelDisaridanLayout.createSequentialGroup()
                .addGroup(jPanelDisaridanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDisaridanLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButtonCezaGoruntuleDisaridan, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDisaridanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelOdenecekDisaridan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanelDisaridanLayout.setVerticalGroup(
            jPanelDisaridanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDisaridanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDisaridanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDisaridanTC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCezaGoruntuleDisaridan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelOdenecekDisaridan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOgretmen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jRadioButtonOgrenci)
                            .addGap(18, 18, 18)
                            .addComponent(jRadioButtonOgretmen)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonDisaridan)))
                    .addComponent(jPanelOgrenci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelDisaridan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonOgretmen)
                    .addComponent(jRadioButtonOgrenci)
                    .addComponent(jRadioButtonDisaridan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelOgrenci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelOgretmen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDisaridan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanelOdenecekOgrenci.setVisible(true);
        String aranacak = jTextFieldTC.getText();
        kim = aranacak;
        //System.out.println(aranacak);
        int toplamCezaGunu = 0;
            try {
                if(baglanti.isClosed()){
                    DBBaglan();
                }
                
                String sql2 = "select * from AYARLAR where UYE_TUR='öğrenci'";
                ResultSet rs2 = ifade.executeQuery(sql2);
                rs2.next();
                int _kac_gun = rs2.getInt("KAC_GUN");
                int _ceza = rs2.getInt("CEZA");
                
                String sql = "select * from OGRENCI_ODUNC where O_VERILEN='"+aranacak+"' and O_KAYNAK_DURUMU=true";
                ResultSet rs = ifade.executeQuery(sql);
                String timeStamp = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
                
                while(rs.next()){
                    long kac_gun = time(rs.getString("O_VERILIS_TARIH"), rs.getString("O_IADE_TARIH"));
                    if(kac_gun > _kac_gun){
                        int kac = toIntExact(kac_gun) - _kac_gun;
                        toplamCezaGunu += kac;
                    }
                }
                int kurus = toplamCezaGunu*_ceza%100;
                int lira = toplamCezaGunu*_ceza/100;
                String odenecek = Integer.toString(lira)+" lira "+Integer.toString(kurus)+" kuruş";
                jLabelToplamCeza.setText(odenecek);
                //jLabelToplamCeza.setVisible(true);
                //jLabel2.setVisible(true);
                //jButtonCezayiode.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(CezaOdeme.class.getName()).log(Level.SEVERE, null, ex);
            } finally{
                try {
                    baglanti.close();
                } catch (SQLException ex) {
                    Logger.getLogger(CezaOdeme.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCezayiodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCezayiodeActionPerformed
        try {
            if(baglanti.isClosed()){
                DBBaglan();    
            }
        } catch (SQLException ex) {
            Logger.getLogger(CezaOdeme.class.getName()).log(Level.SEVERE, null, ex);
        }
        String sql = "delete from OGRENCI_ODUNC where O_VERILEN='"+kim+"' and O_KAYNAK_DURUMU=true";
        try {
            ifade.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(CezaOdeme.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                baglanti.close();
            } catch (SQLException ex) {
                Logger.getLogger(CezaOdeme.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        this.dispose();
    }//GEN-LAST:event_jButtonCezayiodeActionPerformed

    private void jRadioButtonOgretmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOgretmenActionPerformed
        jPanelOgrenci.setVisible(false);
        jPanelOdenecekOgrenci.setVisible(false);
        jPanelOgretmen.setVisible(true);
        jPanelOdenecekOgretmen.setVisible(false);
        jPanelDisaridan.setVisible(false);
        jPanelOdenecekDisaridan.setVisible(false);
    }//GEN-LAST:event_jRadioButtonOgretmenActionPerformed

    private void jRadioButtonOgrenciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOgrenciActionPerformed
        jPanelOgrenci.setVisible(true);
        jPanelOdenecekOgrenci.setVisible(false);
        jPanelOgretmen.setVisible(false);
        jPanelOdenecekOgretmen.setVisible(false);
        jPanelDisaridan.setVisible(false);
        jPanelOdenecekDisaridan.setVisible(false);
    }//GEN-LAST:event_jRadioButtonOgrenciActionPerformed

    private void jTextFieldOgretmenTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOgretmenTCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOgretmenTCActionPerformed

    private void jButtonCezaGoruntuleOgretmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCezaGoruntuleOgretmenActionPerformed
        jPanelOdenecekOgretmen.setVisible(true);
        String aranacak = jTextFieldOgretmenTC.getText();
        kim = aranacak;
        //System.out.println(aranacak);
        int toplamCezaGunu = 0;
            try {
                if(baglanti.isClosed()){
                    DBBaglan();
                }
                
                String sql2 = "select * from AYARLAR where UYE_TUR='öğretmen'";
                ResultSet rs2 = ifade.executeQuery(sql2);
                rs2.next();
                int _kac_gun = rs2.getInt("KAC_GUN");
                int _ceza = rs2.getInt("CEZA");
                
                String sql = "select * from OGRETMEN_ODUNC where O_VERILEN='"+aranacak+"' and O_KAYNAK_DURUMU=true";
                ResultSet rs = ifade.executeQuery(sql);
                String timeStamp = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
                
                while(rs.next()){
                    long kac_gun = time(rs.getString("O_VERILIS_TARIH"), rs.getString("O_IADE_TARIH"));
                    if(kac_gun > _kac_gun){
                        int kac = toIntExact(kac_gun) - _kac_gun;
                        toplamCezaGunu += kac;
                    }
                }
                int kurus = toplamCezaGunu*_ceza%100;
                int lira = toplamCezaGunu*_ceza/100;
                String odenecek = Integer.toString(lira)+" lira "+Integer.toString(kurus)+" kuruş";
                jLabelToplamCezaOgretmen.setText(odenecek);
            } catch (SQLException ex) {
                Logger.getLogger(CezaOdeme.class.getName()).log(Level.SEVERE, null, ex);
            } finally{
                try {
                    baglanti.close();
                } catch (SQLException ex) {
                    Logger.getLogger(CezaOdeme.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_jButtonCezaGoruntuleOgretmenActionPerformed

    private void jButtonCezayiodeOgretmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCezayiodeOgretmenActionPerformed
        try {
            if(baglanti.isClosed()){
                DBBaglan();    
            }
        } catch (SQLException ex) {
            Logger.getLogger(CezaOdeme.class.getName()).log(Level.SEVERE, null, ex);
        }
        String sql = "delete from OGRETMEN_ODUNC where O_VERILEN='"+kim+"' and O_KAYNAK_DURUMU=true";
        try {
            ifade.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(CezaOdeme.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                baglanti.close();
            } catch (SQLException ex) {
                Logger.getLogger(CezaOdeme.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        this.dispose();
    }//GEN-LAST:event_jButtonCezayiodeOgretmenActionPerformed

    private void jTextFieldDisaridanTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDisaridanTCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDisaridanTCActionPerformed

    private void jButtonCezaGoruntuleDisaridanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCezaGoruntuleDisaridanActionPerformed
        jPanelOdenecekDisaridan.setVisible(true);
        String aranacak = jTextFieldDisaridanTC.getText();
        kim = aranacak;
        //System.out.println(aranacak);
        int toplamCezaGunu = 0;
            try {
                if(baglanti.isClosed()){
                    DBBaglan();
                }
                
                String sql2 = "select * from AYARLAR where UYE_TUR='dışarıdan'";
                ResultSet rs2 = ifade.executeQuery(sql2);
                rs2.next();
                int _kac_gun = rs2.getInt("KAC_GUN");
                int _ceza = rs2.getInt("CEZA");
                
                String sql = "select * from DISARIDAN_ODUNC where O_VERILEN='"+aranacak+"' and O_KAYNAK_DURUMU=true";
                ResultSet rs = ifade.executeQuery(sql);
                String timeStamp = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
                
                while(rs.next()){
                    long kac_gun = time(rs.getString("O_VERILIS_TARIH"), rs.getString("O_IADE_TARIH"));
                    if(kac_gun > _kac_gun){
                        int kac = toIntExact(kac_gun) - _kac_gun;
                        toplamCezaGunu += kac;
                    }
                }
                int kurus = toplamCezaGunu*_ceza%100;
                int lira = toplamCezaGunu*_ceza/100;
                String odenecek = Integer.toString(lira)+" lira "+Integer.toString(kurus)+" kuruş";
                jLabelToplamCezaDisaridan.setText(odenecek);
            } catch (SQLException ex) {
                Logger.getLogger(CezaOdeme.class.getName()).log(Level.SEVERE, null, ex);
            } finally{
                try {
                    baglanti.close();
                } catch (SQLException ex) {
                    Logger.getLogger(CezaOdeme.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_jButtonCezaGoruntuleDisaridanActionPerformed

    private void jButtonCezayiodeDisaridanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCezayiodeDisaridanActionPerformed
        try {
            if(baglanti.isClosed()){
                DBBaglan();    
            }
        } catch (SQLException ex) {
            Logger.getLogger(CezaOdeme.class.getName()).log(Level.SEVERE, null, ex);
        }
        String sql = "delete from DISARIDAN_ODUNC where O_VERILEN='"+kim+"' and O_KAYNAK_DURUMU=true";
        try {
            ifade.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(CezaOdeme.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                baglanti.close();
            } catch (SQLException ex) {
                Logger.getLogger(CezaOdeme.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        this.dispose();
    }//GEN-LAST:event_jButtonCezayiodeDisaridanActionPerformed

    private void jRadioButtonDisaridanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDisaridanActionPerformed
        jPanelOgrenci.setVisible(false);
        jPanelOgretmen.setVisible(false);
        jPanelDisaridan.setVisible(true);
        jPanelOdenecekDisaridan.setVisible(false);
    }//GEN-LAST:event_jRadioButtonDisaridanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CezaOdeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CezaOdeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CezaOdeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CezaOdeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CezaOdeme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCezaGoruntuleDisaridan;
    private javax.swing.JButton jButtonCezaGoruntuleOgretmen;
    private javax.swing.JButton jButtonCezayiode;
    private javax.swing.JButton jButtonCezayiodeDisaridan;
    private javax.swing.JButton jButtonCezayiodeOgretmen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelToplamCeza;
    private javax.swing.JLabel jLabelToplamCezaDisaridan;
    private javax.swing.JLabel jLabelToplamCezaOgretmen;
    private javax.swing.JPanel jPanelDisaridan;
    private javax.swing.JPanel jPanelOdenecekDisaridan;
    private javax.swing.JPanel jPanelOdenecekOgrenci;
    private javax.swing.JPanel jPanelOdenecekOgretmen;
    private javax.swing.JPanel jPanelOgrenci;
    private javax.swing.JPanel jPanelOgretmen;
    private javax.swing.JRadioButton jRadioButtonDisaridan;
    private javax.swing.JRadioButton jRadioButtonOgrenci;
    private javax.swing.JRadioButton jRadioButtonOgretmen;
    private javax.swing.JTextField jTextFieldDisaridanTC;
    private javax.swing.JTextField jTextFieldOgretmenTC;
    private javax.swing.JTextField jTextFieldTC;
    // End of variables declaration//GEN-END:variables
}
