package kutuphane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hatice Ertürk
 */
public class kaynak_ara extends javax.swing.JFrame {
    private int neye_gore = 0;
    private Connection baglanti;
    private Statement ifade;
    
    public kaynak_ara() {
        initComponents();
        baslangic();
        DBBaglan();
    }
    
    private void baslangic(){
        buttonGroup1.add(jRadioButtonAd);
        buttonGroup1.add(jRadioButtonYayinEvi);
        buttonGroup1.add(jRadioButtonYazar);
        buttonGroup1.add(jRadioButtonBasimYili);
        buttonGroup1.add(jRadioButtonHersey);
    }

    private void DBBaglan(){
        String baglantiUrl = "jdbc:derby://localhost:1527/Kutuphane";
        String userName = "hatice";
        String password = "123";
        
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            baglanti = DriverManager.getConnection(baglantiUrl,userName,password);
            ifade = baglanti.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
        catch (ClassNotFoundException e){
            e.printStackTrace();
        }
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextFieldKaynakArama = new javax.swing.JTextField();
        jButtonAra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKitaplar = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonAd = new javax.swing.JRadioButton();
        jRadioButtonYayinEvi = new javax.swing.JRadioButton();
        jRadioButtonYazar = new javax.swing.JRadioButton();
        jRadioButtonBasimYili = new javax.swing.JRadioButton();
        jRadioButtonHersey = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        setResizable(false);

        jButtonAra.setText("ARA");
        jButtonAra.setBorder(null);
        jButtonAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAraActionPerformed(evt);
            }
        });

        jTableKitaplar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tür", "Barkod", "Adı", "Yazar", "Boyut(Sayfa/MB)", "Yayın Evi", "Basım Yılı"
            }
        ));
        jScrollPane1.setViewportView(jTableKitaplar);

        jLabel1.setText("Neye Göre Arama Yapmak İstediğinizi Seçiniz");

        jLabel2.setText("Arama Yapacağınız Kaynağı Giriniz");

        jRadioButtonAd.setText("Ad");
        jRadioButtonAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAdActionPerformed(evt);
            }
        });

        jRadioButtonYayinEvi.setText("Yayın Evi");
        jRadioButtonYayinEvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonYayinEviActionPerformed(evt);
            }
        });

        jRadioButtonYazar.setText("Yazar");
        jRadioButtonYazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonYazarActionPerformed(evt);
            }
        });

        jRadioButtonBasimYili.setText("Basım Yılı");
        jRadioButtonBasimYili.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBasimYiliActionPerformed(evt);
            }
        });

        jRadioButtonHersey.setText("Her şey");
        jRadioButtonHersey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHerseyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(260, 260, 260)
                                .addComponent(jButtonAra, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonAd)
                                        .addGap(6, 6, 6)
                                        .addComponent(jRadioButtonYayinEvi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonYazar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonBasimYili)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonHersey))
                                    .addComponent(jTextFieldKaynakArama))))
                        .addGap(0, 251, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldKaynakArama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAd)
                    .addComponent(jRadioButtonYayinEvi)
                    .addComponent(jRadioButtonYazar)
                    .addComponent(jRadioButtonBasimYili)
                    .addComponent(jRadioButtonHersey))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButtonAra, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAraActionPerformed
        String aranacak = jTextFieldKaynakArama.getText();
        
        try {
            if(baglanti.isClosed()){
                DBBaglan();
            }
            if(neye_gore == 1){
                String sql = "select (select TUR_AD from KAYNAK_TUR where TUR_ID=KAYNAKLAR.TUR_ID), BARKOD, AD, YAZAR, BOYUT, YAYIN_EVI, BASIM_YILI from KAYNAKLAR where AD LIKE '%"+aranacak+"%'";
                ResultSet rs = ifade.executeQuery(sql);
                int kacsutun = rs.getMetaData().getColumnCount(); //veritabanında kaç tane sütün olduğunu söylüyor.
                
                DefaultTableModel model = (DefaultTableModel) jTableKitaplar.getModel();//veri ekleyeceğimiz ortamı oluşturduk.
                model.setRowCount(0);//butona her tıklanıldığında aynı şeyi eklememesi için tablo içeriğini sıfırlar.

                while(rs.next()){
                    Object[] row = new Object[kacsutun];
                    for(int i=0;i<kacsutun;i++){
                        row[i] = rs.getObject(i+1);
                    }
                    model.addRow(row);
                }
            }
            else if(neye_gore == 2){
                String sql = "select (select TUR_AD from KAYNAK_TUR where TUR_ID=KAYNAKLAR.TUR_ID), BARKOD, AD, YAZAR, BOYUT, YAYIN_EVI, BASIM_YILI from KAYNAKLAR where YAYIN_EVI LIKE '%"+aranacak+"%'";
                ResultSet rs = ifade.executeQuery(sql);
                int kacsutun = rs.getMetaData().getColumnCount(); //veritabanında kaç tane sütün olduğunu söylüyor.
                
                DefaultTableModel model = (DefaultTableModel) jTableKitaplar.getModel();//veri ekleyeceğimiz ortamı oluşturduk.
                model.setRowCount(0);//butona her tıklanıldığında aynı şeyi eklememesi için tablo içeriğini sıfırlar.

                while(rs.next()){
                    Object[] row = new Object[kacsutun];
                    for(int i=0;i<kacsutun;i++){
                        row[i] = rs.getObject(i+1);
                    }
                    model.addRow(row);
                }
            }
            else if(neye_gore == 3){
                String sql = "select (select TUR_AD from KAYNAK_TUR where TUR_ID=KAYNAKLAR.TUR_ID), BARKOD, AD, YAZAR, BOYUT, YAYIN_EVI, BASIM_YILI from KAYNAKLAR where YAZAR LIKE '%"+aranacak+"%'";
                ResultSet rs = ifade.executeQuery(sql);
                int kacsutun = rs.getMetaData().getColumnCount(); //veritabanında kaç tane sütün olduğunu söylüyor.
                
                DefaultTableModel model = (DefaultTableModel) jTableKitaplar.getModel();//veri ekleyeceğimiz ortamı oluşturduk.
                model.setRowCount(0);//butona her tıklanıldığında aynı şeyi eklememesi için tablo içeriğini sıfırlar.

                while(rs.next()){
                    Object[] row = new Object[kacsutun];
                    for(int i=0;i<kacsutun;i++){
                        row[i] = rs.getObject(i+1);
                    }
                    model.addRow(row);
                }
            }
            else if(neye_gore == 4){
                String sql = "select (select TUR_AD from KAYNAK_TUR where TUR_ID=KAYNAKLAR.TUR_ID), BARKOD, AD, YAZAR, BOYUT, YAYIN_EVI, BASIM_YILI from KAYNAKLAR where BASIM_YILI LIKE '%"+aranacak+"%'";
                ResultSet rs = ifade.executeQuery(sql);
                int kacsutun = rs.getMetaData().getColumnCount(); //veritabanında kaç tane sütün olduğunu söylüyor.
                
                DefaultTableModel model = (DefaultTableModel) jTableKitaplar.getModel();//veri ekleyeceğimiz ortamı oluşturduk.
                model.setRowCount(0);//butona her tıklanıldığında aynı şeyi eklememesi için tablo içeriğini sıfırlar.

                while(rs.next()){
                    Object[] row = new Object[kacsutun];
                    for(int i=0;i<kacsutun;i++){
                        row[i] = rs.getObject(i+1);
                    }
                    model.addRow(row);
                }
            }
            else if(neye_gore == 5){
                String sql = "select (select TUR_AD from KAYNAK_TUR where TUR_ID=KAYNAKLAR.TUR_ID), BARKOD, AD, YAZAR, BOYUT, YAYIN_EVI, BASIM_YILI from KAYNAKLAR where BARKOD LIKE '%"+aranacak+
                                "%' OR AD LIKE '%"+aranacak+"%' OR BOYUT LIKE '%"+aranacak+
                                "%' OR YAYIN_EVI LIKE '%"+aranacak+"%' OR YAZAR LIKE '%"+aranacak+
                                "%' OR BASIM_YILI LIKE '%"+aranacak+"%'";
                ResultSet rs = ifade.executeQuery(sql);
                int kacsutun = rs.getMetaData().getColumnCount(); //veritabanında kaç tane sütün olduğunu söylüyor.
                
                DefaultTableModel model = (DefaultTableModel) jTableKitaplar.getModel();//veri ekleyeceğimiz ortamı oluşturduk.
                model.setRowCount(0);//butona her tıklanıldığında aynı şeyi eklememesi için tablo içeriğini sıfırlar.

                while(rs.next()){
                    Object[] row = new Object[kacsutun];
                    for(int i=0;i<kacsutun;i++){
                        row[i] = rs.getObject(i+1);
                    }
                    model.addRow(row);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(kaynak_ara.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                baglanti.close();
            } catch (SQLException ex) {
                Logger.getLogger(kaynak_ara.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonAraActionPerformed

    private void jRadioButtonAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAdActionPerformed
        neye_gore = 1;
    }//GEN-LAST:event_jRadioButtonAdActionPerformed

    private void jRadioButtonYayinEviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonYayinEviActionPerformed
        neye_gore = 2;
    }//GEN-LAST:event_jRadioButtonYayinEviActionPerformed

    private void jRadioButtonYazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonYazarActionPerformed
        neye_gore = 3;
    }//GEN-LAST:event_jRadioButtonYazarActionPerformed

    private void jRadioButtonBasimYiliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBasimYiliActionPerformed
        neye_gore = 4;
    }//GEN-LAST:event_jRadioButtonBasimYiliActionPerformed

    private void jRadioButtonHerseyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHerseyActionPerformed
        neye_gore = 5;
    }//GEN-LAST:event_jRadioButtonHerseyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kaynak_ara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kaynak_ara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kaynak_ara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kaynak_ara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kaynak_ara().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButtonAd;
    private javax.swing.JRadioButton jRadioButtonBasimYili;
    private javax.swing.JRadioButton jRadioButtonHersey;
    private javax.swing.JRadioButton jRadioButtonYayinEvi;
    private javax.swing.JRadioButton jRadioButtonYazar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKitaplar;
    private javax.swing.JTextField jTextFieldKaynakArama;
    // End of variables declaration//GEN-END:variables
}
