package kutuphane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Hatice Ertürk
 */
public class uye_sil extends javax.swing.JFrame {
    private Connection baglanti;
    private Statement ifade;
    int silinecekTip = 1;
    
    public uye_sil() {
        initComponents();
        baslangic();
        DBBaglan();
    }
    
    private void baslangic(){
        jPanelUyeAra.setVisible(true);
        jPanelUyeBilgi.setVisible(false);
    }

    private void DBBaglan(){
        String baglantiUrl = "jdbc:derby://localhost:1527/Kutuphane";
        String userName = "hatice";
        String password = "123";
        
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            baglanti = DriverManager.getConnection(baglantiUrl,userName,password);
            ifade = baglanti.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
        catch (ClassNotFoundException e){
            e.printStackTrace();
        }
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelUyeAra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldOgrAra = new javax.swing.JTextField();
        jButtonUyeAra = new javax.swing.JButton();
        jPanelUyeBilgi = new javax.swing.JPanel();
        jLabelUyeBilgileri = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonUyeSil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(400, 150));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabel1.setText("Silinecek Üyenin TC/Numara Giriniz ");

        jTextFieldOgrAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOgrAraActionPerformed(evt);
            }
        });

        jButtonUyeAra.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButtonUyeAra.setText("ARA");
        jButtonUyeAra.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonUyeAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUyeAraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUyeAraLayout = new javax.swing.GroupLayout(jPanelUyeAra);
        jPanelUyeAra.setLayout(jPanelUyeAraLayout);
        jPanelUyeAraLayout.setHorizontalGroup(
            jPanelUyeAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUyeAraLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelUyeAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanelUyeAraLayout.createSequentialGroup()
                        .addComponent(jTextFieldOgrAra, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButtonUyeAra, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanelUyeAraLayout.setVerticalGroup(
            jPanelUyeAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUyeAraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUyeAraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUyeAraLayout.createSequentialGroup()
                        .addComponent(jTextFieldOgrAra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(jPanelUyeAraLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jButtonUyeAra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabelUyeBilgileri.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabelUyeBilgileri.setText("ÜYE BİLGİLERİ");

        jLabel3.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N

        jButtonUyeSil.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButtonUyeSil.setText("ÜYEYİ SİL");
        jButtonUyeSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUyeSilActionPerformed(evt);
            }
        });

        jLabel2.setText("TC / Okul Numarası            : ");

        jLabel8.setText("Adı                                     : ");

        jLabel9.setText("Soyadı                               : ");

        jLabel10.setText("Mail Adresi                         : ");

        jLabel11.setText("Okul/Çalışılan Yer/Adres    : ");

        javax.swing.GroupLayout jPanelUyeBilgiLayout = new javax.swing.GroupLayout(jPanelUyeBilgi);
        jPanelUyeBilgi.setLayout(jPanelUyeBilgiLayout);
        jPanelUyeBilgiLayout.setHorizontalGroup(
            jPanelUyeBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUyeBilgiLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(jButtonUyeSil, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(jPanelUyeBilgiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUyeBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelUyeBilgiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelUyeBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelUyeBilgiLayout.createSequentialGroup()
                        .addGroup(jPanelUyeBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelUyeBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
        );
        jPanelUyeBilgiLayout.setVerticalGroup(
            jPanelUyeBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUyeBilgiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUyeBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUyeBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUyeBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUyeBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUyeBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUyeBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUyeSil)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanelUyeAra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanelUyeBilgi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanelUyeAra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelUyeBilgi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUyeAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUyeAraActionPerformed
        //bu butona tıklanınca veritabanından yazılan numaraya göre üyenin bilgileri alıncak ve
        //üye bilgileri paneli görünür yapılıp oraya yazılacak.       
        jPanelUyeAra.setVisible(true);
        jPanelUyeBilgi.setVisible(true);
        
        String silinecek = jTextFieldOgrAra.getText();
        try {
            if(baglanti.isClosed()){
                DBBaglan();
            }
            boolean uyeVarmi = true;
            String sql = "select * from OGRENCI_UYE where OKUL_NO='"+silinecek+"'";
          
            ResultSet rs = ifade.executeQuery(sql);
            jLabelUyeBilgileri.setText("ÖĞRENCİ ÜYE BİLGİLERİ");
            if(!rs.last()) //Eger ogrenci tablosunda boyle bir veri yoksa buraya girecek. 
            {   
                silinecekTip = 2;
                sql = "select * from OGRETMEN_UYE where TC='"+silinecek+"'"; //sirada ogretmen tablosunda olup olmadigina bakmakta...
                rs = ifade.executeQuery(sql);
                jLabelUyeBilgileri.setText("ÖĞRETMEN ÜYE BİLGİLERİ");
                if(!rs.last()) //Eger ogretmen tablosunda boyle bir veri yoksa buraya girecek.
                {
                    silinecekTip = 3;
                    sql = "select * from DISARIDAN_UYE where TC='"+silinecek+"'"; //sirada disaridan uye tablosunda olup olmadigina bakmakta...
                    rs = ifade.executeQuery(sql);
                    jLabelUyeBilgileri.setText("DIŞARIDAN ÜYE BİLGİLERİ");
                    if(!rs.last()) 
                    {
                        jLabelUyeBilgileri.setText("ÜYE BULUNAMADI");
                        uyeVarmi = false;
                        jButtonUyeSil.setVisible(false);
                    }
                }
            }
            
            //rs.next(); //zaten yukarıda rs.last diyince okuyoruz veriyi bu sefer burada okunacak veri kalmıyor.
            if(uyeVarmi) {    
                jLabel3.setText(rs.getString(1));
                jLabel4.setText(rs.getString(2));
                jLabel5.setText(rs.getString(3));
                jLabel6.setText(rs.getString(4));
                jLabel7.setText(rs.getString(5));
            }
        } catch (SQLException ex) {
            Logger.getLogger(uye_sil.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            try {
                baglanti.close();
            } catch (SQLException ex) {
                Logger.getLogger(uye_sil.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jButtonUyeAraActionPerformed

    private void jButtonUyeSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUyeSilActionPerformed
        //üye sil butonuna tıklanıldığında veritabanında bu üye silinecek.
        try {
            if(baglanti.isClosed()){
                DBBaglan();
            }
        } catch (SQLException ex) {
            Logger.getLogger(uye_sil.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String uye = jLabel3.getText();
        if(silinecekTip == 1){
            String sql = "delete from OGRENCI_UYE where OKUL_NO='"+uye+"'";
            try {
                ifade.executeUpdate(sql);
            } catch (SQLException ex) {
                Logger.getLogger(uye_sil.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(silinecekTip == 2){
            String sql = "delete from OGRETMEN_UYE where TC='"+uye+"'";
            try {
                ifade.executeUpdate(sql);
            } catch (SQLException ex) {
                Logger.getLogger(uye_sil.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            String sql = "delete from DISARIDAN_UYE where TC='"+uye+"'";
            try {
                ifade.executeUpdate(sql);
            } catch (SQLException ex) {
                Logger.getLogger(uye_sil.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        this.dispose();
    }//GEN-LAST:event_jButtonUyeSilActionPerformed

    private void jTextFieldOgrAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOgrAraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOgrAraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uye_sil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uye_sil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uye_sil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uye_sil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uye_sil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUyeAra;
    private javax.swing.JButton jButtonUyeSil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelUyeBilgileri;
    private javax.swing.JPanel jPanelUyeAra;
    private javax.swing.JPanel jPanelUyeBilgi;
    private javax.swing.JTextField jTextFieldOgrAra;
    // End of variables declaration//GEN-END:variables
}
